/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Claim {
  'id' : bigint,
  'title' : string,
  'imageUrls' : Array<string>,
  'urls' : Array<string>,
  'description' : string,
  'timestamp' : bigint,
  'category' : string,
  'sessionId' : string,
}
export interface Evidence {
  'id' : bigint,
  'imageUrls' : Array<string>,
  'text' : string,
  'urls' : Array<string>,
  'claimId' : bigint,
  'timestamp' : bigint,
  'sessionId' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'createClaim' : ActorMethod<
    [string, string, string, string, Array<string>, Array<string>],
    undefined
  >,
  'generateSessionId' : ActorMethod<[], string>,
  'getAllClaims' : ActorMethod<[], Array<Claim>>,
  'getClaimById' : ActorMethod<[bigint], Claim>,
  'getClaimsByCategory' : ActorMethod<[string], Array<Claim>>,
  'getEvidenceForClaim' : ActorMethod<[bigint], Array<Evidence>>,
  'getEvidenceVoteTally' : ActorMethod<[bigint], { 'netScore' : bigint }>,
  'getSessionVoteForClaim' : ActorMethod<[bigint, string], [] | [string]>,
  'getSessionVoteForEvidence' : ActorMethod<[bigint, string], [] | [string]>,
  'getVoteTally' : ActorMethod<
    [bigint],
    { 'trueCount' : bigint, 'falseCount' : bigint, 'unverifiedCount' : bigint }
  >,
  'submitEvidence' : ActorMethod<
    [bigint, string, string, Array<string>, Array<string>],
    undefined
  >,
  'submitVote' : ActorMethod<[bigint, string, string], undefined>,
  'voteEvidence' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];