/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Claim = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'authorUsername' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'urls' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'ogThumbnailUrl' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const TrustedSource = IDL.Record({
  'id' : IDL.Nat,
  'adminOverrideNote' : IDL.Text,
  'aboutBlurb' : IDL.Text,
  'domain' : IDL.Text,
  'sourceType' : IDL.Text,
  'adminOverride' : IDL.Bool,
  'timestamp' : IDL.Int,
  'pinnedAdminComment' : IDL.Text,
  'suggestedByUsername' : IDL.Text,
});
export const PrivacySettings = IDL.Record({
  'showVotes' : IDL.Bool,
  'showClaims' : IDL.Bool,
  'showReputation' : IDL.Bool,
  'showSources' : IDL.Bool,
  'showEvidence' : IDL.Bool,
  'showComments' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'privacySettings' : PrivacySettings,
  'username' : IDL.Text,
  'joinDate' : IDL.Int,
  'avatarUrl' : IDL.Text,
  'usernameLastChanged' : IDL.Int,
  'lastActive' : IDL.Int,
});
export const Vote = IDL.Record({
  'claimId' : IDL.Nat,
  'verdict' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Evidence = IDL.Record({
  'id' : IDL.Nat,
  'authorUsername' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'text' : IDL.Text,
  'urls' : IDL.Vec(IDL.Text),
  'claimId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Text,
  'evidenceType' : IDL.Text,
});
export const Reply = IDL.Record({
  'id' : IDL.Nat,
  'authorUsername' : IDL.Text,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
  'parentReplyId' : IDL.Nat,
  'sessionId' : IDL.Text,
  'evidenceId' : IDL.Nat,
});
export const ReputationEvent = IDL.Record({
  'action' : IDL.Text,
  'timestamp' : IDL.Int,
  'points' : IDL.Int,
});
export const SourceComment = IDL.Record({
  'id' : IDL.Nat,
  'authorUsername' : IDL.Text,
  'parentCommentId' : IDL.Nat,
  'text' : IDL.Text,
  'sourceId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Text,
});
export const UserVote = IDL.Record({
  'authorUsername' : IDL.Text,
  'claimTitle' : IDL.Text,
  'claimId' : IDL.Nat,
  'verdict' : IDL.Text,
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReply' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addReputationEvent' : IDL.Func([IDL.Principal, IDL.Text, IDL.Int], [], []),
  'addSourceComment' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteClaim' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteEvidence' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteReply' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteSourceComment' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteVote' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminFetchAboutBlurb' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllClaims' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
  'adminGetAllSources' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TrustedSource)],
      ['query'],
    ),
  'adminGetAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'adminGetVotesForClaim' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(Vote)],
      ['query'],
    ),
  'adminOverrideSource' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminRemoveSource' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetPinnedComment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClaim' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, PrivacySettings],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'generateSessionId' : IDL.Func([], [IDL.Text], []),
  'getAllClaims' : IDL.Func([], [IDL.Vec(Claim)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClaimById' : IDL.Func([IDL.Nat], [Claim], ['query']),
  'getClaimsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
  'getEnhancedVoteTally' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'trueFromEvidence' : IDL.Int,
          'unverifiedFromEvidence' : IDL.Int,
          'falseDirect' : IDL.Int,
          'trueCount' : IDL.Int,
          'unverifiedDirect' : IDL.Int,
          'falseFromEvidence' : IDL.Int,
          'trueDirect' : IDL.Int,
          'falseCount' : IDL.Int,
          'unverifiedCount' : IDL.Int,
        }),
      ],
      ['query'],
    ),
  'getEvidenceForClaim' : IDL.Func([IDL.Nat], [IDL.Vec(Evidence)], ['query']),
  'getEvidenceVoteTally' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'netScore' : IDL.Int })],
      ['query'],
    ),
  'getHiddenClaims' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
  'getHiddenEvidence' : IDL.Func([IDL.Text], [IDL.Vec(Evidence)], ['query']),
  'getHiddenReplies' : IDL.Func([IDL.Text], [IDL.Vec(Reply)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getReplies' : IDL.Func([IDL.Nat], [IDL.Vec(Reply)], ['query']),
  'getReplyLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getReplyLikeCounts' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getReplyVoteTally' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'netScore' : IDL.Int })],
      ['query'],
    ),
  'getReportCount' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], ['query']),
  'getReputationEvents' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ReputationEvent)],
      ['query'],
    ),
  'getSessionLikeForReply' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'getSessionLikeForSourceComment' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'getSessionVoteForClaim' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getSessionVoteForEvidence' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getSessionVoteForReply' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getSessionVoteForSource' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getSourceCommentLikeCounts' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getSourceComments' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SourceComment)],
      ['query'],
    ),
  'getSourceCredibilityForUrl' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'isTrusted' : IDL.Bool,
          'domain' : IDL.Text,
          'sourceType' : IDL.Text,
          'bonusPct' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getStatsByUsername' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'activityPoints' : IDL.Int,
          'trustScore' : IDL.Nat,
          'claimCount' : IDL.Nat,
          'replyCount' : IDL.Nat,
          'commentCount' : IDL.Nat,
          'evidenceCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTrustedSources' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Nat,
            'upvotes' : IDL.Nat,
            'adminOverrideNote' : IDL.Text,
            'aboutBlurb' : IDL.Text,
            'isTrusted' : IDL.Bool,
            'domain' : IDL.Text,
            'sourceType' : IDL.Text,
            'adminOverride' : IDL.Bool,
            'timestamp' : IDL.Int,
            'pinnedAdminComment' : IDL.Text,
            'downvotes' : IDL.Nat,
            'suggestedByUsername' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoteTally' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'trueCount' : IDL.Nat,
          'falseCount' : IDL.Nat,
          'unverifiedCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getVotesByUsername' : IDL.Func([IDL.Text], [IDL.Vec(UserVote)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'likeReply' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'likeSourceComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'recordVoteWithUsername' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'reportContent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'reportReply' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'reportSourceComment' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'restoreClaim' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'restoreEvidence' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'restoreReply' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitEvidence' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'submitVote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'suggestTrustedSource' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'updateLastActive' : IDL.Func([IDL.Principal], [], []),
  'voteEvidence' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'voteOnSource' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'voteReply' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Claim = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'authorUsername' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'urls' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'ogThumbnailUrl' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const TrustedSource = IDL.Record({
    'id' : IDL.Nat,
    'adminOverrideNote' : IDL.Text,
    'aboutBlurb' : IDL.Text,
    'domain' : IDL.Text,
    'sourceType' : IDL.Text,
    'adminOverride' : IDL.Bool,
    'timestamp' : IDL.Int,
    'pinnedAdminComment' : IDL.Text,
    'suggestedByUsername' : IDL.Text,
  });
  const PrivacySettings = IDL.Record({
    'showVotes' : IDL.Bool,
    'showClaims' : IDL.Bool,
    'showReputation' : IDL.Bool,
    'showSources' : IDL.Bool,
    'showEvidence' : IDL.Bool,
    'showComments' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'privacySettings' : PrivacySettings,
    'username' : IDL.Text,
    'joinDate' : IDL.Int,
    'avatarUrl' : IDL.Text,
    'usernameLastChanged' : IDL.Int,
    'lastActive' : IDL.Int,
  });
  const Vote = IDL.Record({
    'claimId' : IDL.Nat,
    'verdict' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Evidence = IDL.Record({
    'id' : IDL.Nat,
    'authorUsername' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'text' : IDL.Text,
    'urls' : IDL.Vec(IDL.Text),
    'claimId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Text,
    'evidenceType' : IDL.Text,
  });
  const Reply = IDL.Record({
    'id' : IDL.Nat,
    'authorUsername' : IDL.Text,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
    'parentReplyId' : IDL.Nat,
    'sessionId' : IDL.Text,
    'evidenceId' : IDL.Nat,
  });
  const ReputationEvent = IDL.Record({
    'action' : IDL.Text,
    'timestamp' : IDL.Int,
    'points' : IDL.Int,
  });
  const SourceComment = IDL.Record({
    'id' : IDL.Nat,
    'authorUsername' : IDL.Text,
    'parentCommentId' : IDL.Nat,
    'text' : IDL.Text,
    'sourceId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Text,
  });
  const UserVote = IDL.Record({
    'authorUsername' : IDL.Text,
    'claimTitle' : IDL.Text,
    'claimId' : IDL.Nat,
    'verdict' : IDL.Text,
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReply' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addReputationEvent' : IDL.Func([IDL.Principal, IDL.Text, IDL.Int], [], []),
    'addSourceComment' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteClaim' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteEvidence' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteReply' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteSourceComment' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteVote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminFetchAboutBlurb' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllClaims' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
    'adminGetAllSources' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TrustedSource)],
        ['query'],
      ),
    'adminGetAllUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'adminGetVotesForClaim' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(Vote)],
        ['query'],
      ),
    'adminOverrideSource' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminRemoveSource' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetPinnedComment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClaim' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, PrivacySettings],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'generateSessionId' : IDL.Func([], [IDL.Text], []),
    'getAllClaims' : IDL.Func([], [IDL.Vec(Claim)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClaimById' : IDL.Func([IDL.Nat], [Claim], ['query']),
    'getClaimsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
    'getEnhancedVoteTally' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'trueFromEvidence' : IDL.Int,
            'unverifiedFromEvidence' : IDL.Int,
            'falseDirect' : IDL.Int,
            'trueCount' : IDL.Int,
            'unverifiedDirect' : IDL.Int,
            'falseFromEvidence' : IDL.Int,
            'trueDirect' : IDL.Int,
            'falseCount' : IDL.Int,
            'unverifiedCount' : IDL.Int,
          }),
        ],
        ['query'],
      ),
    'getEvidenceForClaim' : IDL.Func([IDL.Nat], [IDL.Vec(Evidence)], ['query']),
    'getEvidenceVoteTally' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'netScore' : IDL.Int })],
        ['query'],
      ),
    'getHiddenClaims' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
    'getHiddenEvidence' : IDL.Func([IDL.Text], [IDL.Vec(Evidence)], ['query']),
    'getHiddenReplies' : IDL.Func([IDL.Text], [IDL.Vec(Reply)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getReplies' : IDL.Func([IDL.Nat], [IDL.Vec(Reply)], ['query']),
    'getReplyLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getReplyLikeCounts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getReplyVoteTally' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'netScore' : IDL.Int })],
        ['query'],
      ),
    'getReportCount' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], ['query']),
    'getReputationEvents' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ReputationEvent)],
        ['query'],
      ),
    'getSessionLikeForReply' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'getSessionLikeForSourceComment' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'getSessionVoteForClaim' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getSessionVoteForEvidence' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getSessionVoteForReply' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getSessionVoteForSource' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getSourceCommentLikeCounts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getSourceComments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SourceComment)],
        ['query'],
      ),
    'getSourceCredibilityForUrl' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'isTrusted' : IDL.Bool,
            'domain' : IDL.Text,
            'sourceType' : IDL.Text,
            'bonusPct' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getStatsByUsername' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'activityPoints' : IDL.Int,
            'trustScore' : IDL.Nat,
            'claimCount' : IDL.Nat,
            'replyCount' : IDL.Nat,
            'commentCount' : IDL.Nat,
            'evidenceCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTrustedSources' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Nat,
              'upvotes' : IDL.Nat,
              'adminOverrideNote' : IDL.Text,
              'aboutBlurb' : IDL.Text,
              'isTrusted' : IDL.Bool,
              'domain' : IDL.Text,
              'sourceType' : IDL.Text,
              'adminOverride' : IDL.Bool,
              'timestamp' : IDL.Int,
              'pinnedAdminComment' : IDL.Text,
              'downvotes' : IDL.Nat,
              'suggestedByUsername' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoteTally' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'trueCount' : IDL.Nat,
            'falseCount' : IDL.Nat,
            'unverifiedCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getVotesByUsername' : IDL.Func([IDL.Text], [IDL.Vec(UserVote)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'likeReply' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'likeSourceComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'recordVoteWithUsername' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'reportContent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'reportReply' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'reportSourceComment' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'restoreClaim' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'restoreEvidence' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'restoreReply' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitEvidence' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'submitVote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'suggestTrustedSource' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'updateLastActive' : IDL.Func([IDL.Principal], [], []),
    'voteEvidence' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'voteOnSource' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'voteReply' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };