/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Claim {
  'id' : bigint,
  'title' : string,
  'authorUsername' : string,
  'imageUrls' : Array<string>,
  'urls' : Array<string>,
  'description' : string,
  'ogThumbnailUrl' : string,
  'timestamp' : bigint,
  'category' : string,
  'sessionId' : string,
}
export interface Evidence {
  'id' : bigint,
  'authorUsername' : string,
  'imageUrls' : Array<string>,
  'text' : string,
  'urls' : Array<string>,
  'claimId' : bigint,
  'timestamp' : bigint,
  'sessionId' : string,
  'evidenceType' : string,
}
export interface PrivacySettings {
  'showVotes' : boolean,
  'showClaims' : boolean,
  'showReputation' : boolean,
  'showSources' : boolean,
  'showEvidence' : boolean,
  'showComments' : boolean,
}
export interface Reply {
  'id' : bigint,
  'authorUsername' : string,
  'text' : string,
  'timestamp' : bigint,
  'parentReplyId' : bigint,
  'sessionId' : string,
  'evidenceId' : bigint,
}
export interface ReputationEvent {
  'action' : string,
  'timestamp' : bigint,
  'points' : bigint,
}
export interface SourceComment {
  'id' : bigint,
  'authorUsername' : string,
  'parentCommentId' : bigint,
  'text' : string,
  'sourceId' : bigint,
  'timestamp' : bigint,
  'sessionId' : string,
}
export interface UserProfile {
  'bio' : string,
  'privacySettings' : PrivacySettings,
  'username' : string,
  'joinDate' : bigint,
  'avatarUrl' : string,
  'usernameLastChanged' : bigint,
  'lastActive' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserVote {
  'authorUsername' : string,
  'claimTitle' : string,
  'claimId' : bigint,
  'verdict' : string,
  'timestamp' : bigint,
  'sessionId' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReply' : ActorMethod<
    [bigint, bigint, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addReputationEvent' : ActorMethod<[Principal, string, bigint], undefined>,
  'addSourceComment' : ActorMethod<
    [bigint, bigint, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteClaim' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteEvidence' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteReply' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminFetchAboutBlurb' : ActorMethod<
    [bigint, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminOverrideSource' : ActorMethod<
    [bigint, boolean, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminRemoveSource' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetPinnedComment' : ActorMethod<
    [bigint, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClaim' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      Array<string>,
      string,
    ],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createOrUpdateProfile' : ActorMethod<
    [Principal, string, string, string, PrivacySettings],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'generateSessionId' : ActorMethod<[], string>,
  'getAllClaims' : ActorMethod<[], Array<Claim>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClaimById' : ActorMethod<[bigint], Claim>,
  'getClaimsByCategory' : ActorMethod<[string], Array<Claim>>,
  'getEnhancedVoteTally' : ActorMethod<
    [bigint],
    {
      'trueFromEvidence' : bigint,
      'unverifiedFromEvidence' : bigint,
      'falseDirect' : bigint,
      'trueCount' : bigint,
      'unverifiedDirect' : bigint,
      'falseFromEvidence' : bigint,
      'trueDirect' : bigint,
      'falseCount' : bigint,
      'unverifiedCount' : bigint,
    }
  >,
  'getEvidenceForClaim' : ActorMethod<[bigint], Array<Evidence>>,
  'getEvidenceVoteTally' : ActorMethod<[bigint], { 'netScore' : bigint }>,
  'getHiddenClaims' : ActorMethod<[string], Array<Claim>>,
  'getHiddenEvidence' : ActorMethod<[string], Array<Evidence>>,
  'getHiddenReplies' : ActorMethod<[string], Array<Reply>>,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getProfileByUsername' : ActorMethod<[string], [] | [UserProfile]>,
  'getReplies' : ActorMethod<[bigint], Array<Reply>>,
  'getReplyLikeCount' : ActorMethod<[bigint], bigint>,
  'getReplyLikeCounts' : ActorMethod<[bigint], Array<[bigint, bigint]>>,
  'getReplyVoteTally' : ActorMethod<[bigint], { 'netScore' : bigint }>,
  'getReportCount' : ActorMethod<[bigint, string], bigint>,
  'getReputationEvents' : ActorMethod<[Principal], Array<ReputationEvent>>,
  'getSessionLikeForReply' : ActorMethod<[bigint, string], boolean>,
  'getSessionLikeForSourceComment' : ActorMethod<[bigint, string], boolean>,
  'getSessionVoteForClaim' : ActorMethod<[bigint, string], [] | [string]>,
  'getSessionVoteForEvidence' : ActorMethod<[bigint, string], [] | [string]>,
  'getSessionVoteForReply' : ActorMethod<[bigint, string], [] | [string]>,
  'getSessionVoteForSource' : ActorMethod<[bigint, string], [] | [string]>,
  'getSourceCommentLikeCounts' : ActorMethod<[bigint], Array<[bigint, bigint]>>,
  'getSourceComments' : ActorMethod<[bigint], Array<SourceComment>>,
  'getSourceCredibilityForUrl' : ActorMethod<
    [string],
    {
      'isTrusted' : boolean,
      'domain' : string,
      'sourceType' : string,
      'bonusPct' : bigint,
    }
  >,
  'getStatsByUsername' : ActorMethod<
    [string],
    {
      'activityPoints' : bigint,
      'trustScore' : bigint,
      'claimCount' : bigint,
      'replyCount' : bigint,
      'commentCount' : bigint,
      'evidenceCount' : bigint,
    }
  >,
  'getTrustedSources' : ActorMethod<
    [],
    Array<
      {
        'id' : bigint,
        'upvotes' : bigint,
        'adminOverrideNote' : string,
        'aboutBlurb' : string,
        'isTrusted' : boolean,
        'domain' : string,
        'sourceType' : string,
        'adminOverride' : boolean,
        'timestamp' : bigint,
        'pinnedAdminComment' : string,
        'downvotes' : bigint,
        'suggestedByUsername' : string,
      }
    >
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoteTally' : ActorMethod<
    [bigint],
    { 'trueCount' : bigint, 'falseCount' : bigint, 'unverifiedCount' : bigint }
  >,
  'getVotesByUsername' : ActorMethod<[string], Array<UserVote>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  'likeReply' : ActorMethod<[bigint, string], undefined>,
  'likeSourceComment' : ActorMethod<[bigint, string], undefined>,
  'recordVoteWithUsername' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'reportContent' : ActorMethod<
    [bigint, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'reportReply' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'reportSourceComment' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'restoreClaim' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'restoreEvidence' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'restoreReply' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitEvidence' : ActorMethod<
    [bigint, string, string, string, Array<string>, Array<string>, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'submitVote' : ActorMethod<[bigint, string, string], undefined>,
  'suggestTrustedSource' : ActorMethod<
    [string, string, string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'updateLastActive' : ActorMethod<[Principal], undefined>,
  'voteEvidence' : ActorMethod<[bigint, string, string], undefined>,
  'voteOnSource' : ActorMethod<
    [bigint, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'voteReply' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];