/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Claim = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'urls' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const Evidence = IDL.Record({
  'id' : IDL.Nat,
  'imageUrls' : IDL.Vec(IDL.Text),
  'text' : IDL.Text,
  'urls' : IDL.Vec(IDL.Text),
  'claimId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createClaim' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'generateSessionId' : IDL.Func([], [IDL.Text], []),
  'getAllClaims' : IDL.Func([], [IDL.Vec(Claim)], ['query']),
  'getClaimById' : IDL.Func([IDL.Nat], [Claim], ['query']),
  'getClaimsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
  'getEvidenceForClaim' : IDL.Func([IDL.Nat], [IDL.Vec(Evidence)], ['query']),
  'getEvidenceVoteTally' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'netScore' : IDL.Int })],
      ['query'],
    ),
  'getSessionVoteForClaim' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getSessionVoteForEvidence' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getVoteTally' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'trueCount' : IDL.Nat,
          'falseCount' : IDL.Nat,
          'unverifiedCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'submitEvidence' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'submitVote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'voteEvidence' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Claim = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'urls' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const Evidence = IDL.Record({
    'id' : IDL.Nat,
    'imageUrls' : IDL.Vec(IDL.Text),
    'text' : IDL.Text,
    'urls' : IDL.Vec(IDL.Text),
    'claimId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createClaim' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'generateSessionId' : IDL.Func([], [IDL.Text], []),
    'getAllClaims' : IDL.Func([], [IDL.Vec(Claim)], ['query']),
    'getClaimById' : IDL.Func([IDL.Nat], [Claim], ['query']),
    'getClaimsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Claim)], ['query']),
    'getEvidenceForClaim' : IDL.Func([IDL.Nat], [IDL.Vec(Evidence)], ['query']),
    'getEvidenceVoteTally' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'netScore' : IDL.Int })],
        ['query'],
      ),
    'getSessionVoteForClaim' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getSessionVoteForEvidence' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getVoteTally' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'trueCount' : IDL.Nat,
            'falseCount' : IDL.Nat,
            'unverifiedCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'submitEvidence' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'submitVote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'voteEvidence' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };