/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Claim {
    id: bigint;
    title: string;
    imageUrls: Array<string>;
    urls: Array<string>;
    description: string;
    ogThumbnailUrl: string;
    timestamp: bigint;
    category: string;
    sessionId: string;
}
export interface Reply {
    id: bigint;
    authorUsername: string;
    text: string;
    timestamp: bigint;
    parentReplyId: bigint;
    sessionId: string;
    evidenceId: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface SourceComment {
    id: bigint;
    authorUsername: string;
    parentCommentId: bigint;
    text: string;
    sourceId: bigint;
    timestamp: bigint;
    sessionId: string;
}
export interface Evidence {
    id: bigint;
    imageUrls: Array<string>;
    text: string;
    urls: Array<string>;
    claimId: bigint;
    timestamp: bigint;
    sessionId: string;
    evidenceType: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addReply(evidenceId: bigint, parentReplyId: bigint, text: string, authorUsername: string, sessionId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addSourceComment(sourceId: bigint, parentCommentId: bigint, text: string, authorUsername: string, sessionId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminDeleteClaim(id: bigint, password: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminDeleteEvidence(id: bigint, password: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminDeleteReply(id: bigint, password: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminOverrideSource(sourceId: bigint, approved: boolean, password: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminRemoveSource(sourceId: bigint, password: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createClaim(title: string, description: string, category: string, sessionId: string, imageUrls: Array<string>, urls: Array<string>, ogThumbnailUrl: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    generateSessionId(): Promise<string>;
    getAllClaims(): Promise<Array<Claim>>;
    getClaimById(id: bigint): Promise<Claim>;
    getClaimsByCategory(category: string): Promise<Array<Claim>>;
    getEnhancedVoteTally(claimId: bigint): Promise<{
        trueFromEvidence: bigint;
        unverifiedFromEvidence: bigint;
        falseDirect: bigint;
        trueCount: bigint;
        unverifiedDirect: bigint;
        falseFromEvidence: bigint;
        trueDirect: bigint;
        falseCount: bigint;
        unverifiedCount: bigint;
    }>;
    getEvidenceForClaim(claimId: bigint): Promise<Array<Evidence>>;
    getEvidenceVoteTally(evidenceId: bigint): Promise<{
        netScore: bigint;
    }>;
    getHiddenClaims(password: string): Promise<Array<Claim>>;
    getHiddenEvidence(password: string): Promise<Array<Evidence>>;
    getHiddenReplies(password: string): Promise<Array<Reply>>;
    getReplies(evidenceId: bigint): Promise<Array<Reply>>;
    getReplyLikeCount(replyId: bigint): Promise<bigint>;
    getReplyLikeCounts(evidenceId: bigint): Promise<Array<[bigint, bigint]>>;
    getReplyVoteTally(replyId: bigint): Promise<{
        netScore: bigint;
    }>;
    getReportCount(targetId: bigint, targetType: string): Promise<bigint>;
    getSessionLikeForReply(replyId: bigint, sessionId: string): Promise<boolean>;
    getSessionLikeForSourceComment(commentId: bigint, sessionId: string): Promise<boolean>;
    getSessionVoteForClaim(claimId: bigint, sessionId: string): Promise<string | null>;
    getSessionVoteForEvidence(evidenceId: bigint, sessionId: string): Promise<string | null>;
    getSessionVoteForReply(replyId: bigint, sessionId: string): Promise<string | null>;
    getSessionVoteForSource(sourceId: bigint, sessionId: string): Promise<string | null>;
    getSourceCommentLikeCounts(sourceId: bigint): Promise<Array<[bigint, bigint]>>;
    getSourceComments(sourceId: bigint): Promise<Array<SourceComment>>;
    getSourceCredibilityForUrl(url: string): Promise<{
        isTrusted: boolean;
        domain: string;
        sourceType: string;
        bonusPct: bigint;
    }>;
    getTrustedSources(): Promise<Array<{
        id: bigint;
        upvotes: bigint;
        suggestedBy: string;
        isTrusted: boolean;
        domain: string;
        sourceType: string;
        adminOverride: boolean;
        timestamp: bigint;
        downvotes: bigint;
    }>>;
    getVoteTally(claimId: bigint): Promise<{
        trueCount: bigint;
        falseCount: bigint;
        unverifiedCount: bigint;
    }>;
    likeReply(replyId: bigint, sessionId: string): Promise<void>;
    likeSourceComment(commentId: bigint, sessionId: string): Promise<void>;
    reportContent(targetId: bigint, targetType: string, sessionId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    reportReply(replyId: bigint, sessionId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    reportSourceComment(commentId: bigint, sessionId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    restoreClaim(id: bigint, password: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    restoreEvidence(id: bigint, password: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    restoreReply(id: bigint, password: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitEvidence(claimId: bigint, sessionId: string, text: string, imageUrls: Array<string>, urls: Array<string>, evidenceType: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitVote(claimId: bigint, sessionId: string, verdict: string): Promise<void>;
    suggestTrustedSource(domain: string, sourceType: string, sessionId: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    voteEvidence(evidenceId: bigint, sessionId: string, direction: string): Promise<void>;
    voteOnSource(sourceId: bigint, sessionId: string, direction: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    voteReply(replyId: bigint, sessionId: string, direction: string): Promise<void>;
}
import type { _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addReply(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addReply(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReply(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async addSourceComment(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addSourceComment(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSourceComment(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteClaim(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteClaim(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteClaim(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteEvidence(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteEvidence(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteEvidence(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteReply(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteReply(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteReply(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminOverrideSource(arg0: bigint, arg1: boolean, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminOverrideSource(arg0, arg1, arg2);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminOverrideSource(arg0, arg1, arg2);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRemoveSource(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRemoveSource(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRemoveSource(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createClaim(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>, arg5: Array<string>, arg6: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createClaim(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClaim(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateSessionId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateSessionId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateSessionId();
            return result;
        }
    }
    async getAllClaims(): Promise<Array<Claim>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClaims();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClaims();
            return result;
        }
    }
    async getClaimById(arg0: bigint): Promise<Claim> {
        if (this.processError) {
            try {
                const result = await this.actor.getClaimById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClaimById(arg0);
            return result;
        }
    }
    async getClaimsByCategory(arg0: string): Promise<Array<Claim>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClaimsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClaimsByCategory(arg0);
            return result;
        }
    }
    async getEnhancedVoteTally(arg0: bigint): Promise<{
        trueFromEvidence: bigint;
        unverifiedFromEvidence: bigint;
        falseDirect: bigint;
        trueCount: bigint;
        unverifiedDirect: bigint;
        falseFromEvidence: bigint;
        trueDirect: bigint;
        falseCount: bigint;
        unverifiedCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnhancedVoteTally(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnhancedVoteTally(arg0);
            return result;
        }
    }
    async getEvidenceForClaim(arg0: bigint): Promise<Array<Evidence>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvidenceForClaim(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvidenceForClaim(arg0);
            return result;
        }
    }
    async getEvidenceVoteTally(arg0: bigint): Promise<{
        netScore: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvidenceVoteTally(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvidenceVoteTally(arg0);
            return result;
        }
    }
    async getHiddenClaims(arg0: string): Promise<Array<Claim>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHiddenClaims(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHiddenClaims(arg0);
            return result;
        }
    }
    async getHiddenEvidence(arg0: string): Promise<Array<Evidence>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHiddenEvidence(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHiddenEvidence(arg0);
            return result;
        }
    }
    async getHiddenReplies(arg0: string): Promise<Array<Reply>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHiddenReplies(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHiddenReplies(arg0);
            return result;
        }
    }
    async getReplies(arg0: bigint): Promise<Array<Reply>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReplies(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReplies(arg0);
            return result;
        }
    }
    async getReplyLikeCount(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getReplyLikeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReplyLikeCount(arg0);
            return result;
        }
    }
    async getReplyLikeCounts(arg0: bigint): Promise<Array<[bigint, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReplyLikeCounts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReplyLikeCounts(arg0);
            return result;
        }
    }
    async getReplyVoteTally(arg0: bigint): Promise<{
        netScore: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getReplyVoteTally(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReplyVoteTally(arg0);
            return result;
        }
    }
    async getReportCount(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportCount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportCount(arg0, arg1);
            return result;
        }
    }
    async getSessionLikeForReply(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionLikeForReply(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionLikeForReply(arg0, arg1);
            return result;
        }
    }
    async getSessionLikeForSourceComment(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionLikeForSourceComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionLikeForSourceComment(arg0, arg1);
            return result;
        }
    }
    async getSessionVoteForClaim(arg0: bigint, arg1: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionVoteForClaim(arg0, arg1);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionVoteForClaim(arg0, arg1);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionVoteForEvidence(arg0: bigint, arg1: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionVoteForEvidence(arg0, arg1);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionVoteForEvidence(arg0, arg1);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionVoteForReply(arg0: bigint, arg1: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionVoteForReply(arg0, arg1);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionVoteForReply(arg0, arg1);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionVoteForSource(arg0: bigint, arg1: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionVoteForSource(arg0, arg1);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionVoteForSource(arg0, arg1);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSourceCommentLikeCounts(arg0: bigint): Promise<Array<[bigint, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSourceCommentLikeCounts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSourceCommentLikeCounts(arg0);
            return result;
        }
    }
    async getSourceComments(arg0: bigint): Promise<Array<SourceComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSourceComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSourceComments(arg0);
            return result;
        }
    }
    async getSourceCredibilityForUrl(arg0: string): Promise<{
        isTrusted: boolean;
        domain: string;
        sourceType: string;
        bonusPct: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSourceCredibilityForUrl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSourceCredibilityForUrl(arg0);
            return result;
        }
    }
    async getTrustedSources(): Promise<Array<{
        id: bigint;
        upvotes: bigint;
        suggestedBy: string;
        isTrusted: boolean;
        domain: string;
        sourceType: string;
        adminOverride: boolean;
        timestamp: bigint;
        downvotes: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrustedSources();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrustedSources();
            return result;
        }
    }
    async getVoteTally(arg0: bigint): Promise<{
        trueCount: bigint;
        falseCount: bigint;
        unverifiedCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoteTally(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoteTally(arg0);
            return result;
        }
    }
    async likeReply(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeReply(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeReply(arg0, arg1);
            return result;
        }
    }
    async likeSourceComment(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeSourceComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeSourceComment(arg0, arg1);
            return result;
        }
    }
    async reportContent(arg0: bigint, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.reportContent(arg0, arg1, arg2);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportContent(arg0, arg1, arg2);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async reportReply(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.reportReply(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportReply(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async reportSourceComment(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.reportSourceComment(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportSourceComment(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async restoreClaim(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreClaim(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreClaim(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async restoreEvidence(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreEvidence(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreEvidence(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async restoreReply(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreReply(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreReply(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitEvidence(arg0: bigint, arg1: string, arg2: string, arg3: Array<string>, arg4: Array<string>, arg5: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEvidence(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEvidence(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitVote(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitVote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitVote(arg0, arg1, arg2);
            return result;
        }
    }
    async suggestTrustedSource(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.suggestTrustedSource(arg0, arg1, arg2);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suggestTrustedSource(arg0, arg1, arg2);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async voteEvidence(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.voteEvidence(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voteEvidence(arg0, arg1, arg2);
            return result;
        }
    }
    async voteOnSource(arg0: bigint, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.voteOnSource(arg0, arg1, arg2);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voteOnSource(arg0, arg1, arg2);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async voteReply(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.voteReply(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voteReply(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
